# -*- coding: iso-8859-15 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: minimal.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid

# Window functions

ID_TEXT = 10000
ID_LINE = 10001

def MyDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item2 = wx.StaticBox( parent, -1, "Copyright" )
    item2.SetFont( wx.Font( 16, wx.ROMAN, wx.NORMAL, wx.NORMAL ) )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )
    parent.copyright_sizer = item1
    
    item3 = wx.StaticText( parent, ID_TEXT, "Copyright 2002 T. Coon. 1000,- €.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.SetForegroundColour( wx.BLUE )
    item3.SetFont( wx.Font( 16, wx.ROMAN, wx.NORMAL, wx.NORMAL ) )
    item1.Add( item3, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item4 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item0.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item5 = wx.Button( parent, wx.ID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item0.Add( item5, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


# End of generated file
