#-----------------------------------------------------------------------------
# Perl source generated by wxDesigner from file: minimal.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

use Wx;
use strict;

use Wx qw( wxDefaultSize wxDefaultPosition wxID_OK wxID_CANCEL wxID_YES wxID_EXIT wxID_ABOUT );
use Wx qw( wxVERTICAL wxHORIZONTAL wxALL wxLEFT wxRIGHT wxTOP wxBOTTOM wxCENTRE wxGROW wxADJUST_MINSIZE );
use Wx qw( wxALIGN_RIGHT wxALIGN_BOTTOM wxALIGN_CENTER wxALIGN_CENTER_VERTICAL wxALIGN_CENTER_HORIZONTAL );
use Wx qw( wxLI_HORIZONTAL );

# Window functions

use vars qw($ID_TEXT); $ID_TEXT = 10000;
use vars qw($ID_LINE); $ID_LINE = 10001;

sub MyDialogFunc {
    my( $item0 ) = Wx::BoxSizer->new( wxVERTICAL );
    
    my( $item2 ) = Wx::StaticBox->new( $_[0], -1, "Copyright" );
    my( $item1 ) = Wx::StaticBoxSizer->new( $item2, wxVERTICAL );
    $_[0]->{copyright_sizer} = $item1;
    
    my( $item3 ) = Wx::StaticText->new( $_[0], $main::ID_TEXT, "Copyright 2002 T. Coon. 1000,- ¤.", wxDefaultPosition, wxDefaultSize, 0 );
    $item3->SetForegroundColour( Wx::wxBLUE );
    $item1->AddWindow( $item3, 0, wxALIGN_CENTER|wxALL, 5 );

    $item0->Add( $item1, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item4 ) = Wx::StaticLine->new( $_[0], $main::ID_LINE, wxDefaultPosition, [20,-1], wxLI_HORIZONTAL );
    $item0->AddWindow( $item4, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item5 ) = Wx::Button->new( $_[0], wxID_OK, "OK", wxDefaultPosition, wxDefaultSize, 0 );
    $item0->AddWindow( $item5, 0, wxALIGN_CENTER|wxALL, 5 );

    my( $set_size ) = @_ >= 3 ? $_[2] : 1;
    my( $call_fit ) = @_ >= 2 ? $_[1] : 1;
    if( $set_size == 1 ) {
         $_[0]->SetSizer( $item0 );
         
         if( $call_fit == 1 ) {
             $item0->SetSizeHints( $_[0] );
         }
    }
    
    $item0;
}

# Menu bar functions

# Bitmap functions

use Wx qw( wxNullBitmap wxBITMAP_TYPE_PNG );


# Toolbar functions


# End of generated file
