//------------------------------------------------------------------------------
// Source code generated by wxDesigner from file: derived.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifdef __GNUG__
    #pragma implementation "derived_wdr.h"
#endif

// For compilers that support precompilation
#include "wx/wxprec.h"

#ifdef __BORLANDC__
    #pragma hdrstop
#endif

// Include private header
#include "derived_wdr.h"


// Custom source
#include "derived.h"

// Implement window functions

wxSizer *MyDialogFunc( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxStaticBox *item2 = new wxStaticBox( parent, -1, wxT("Special text controls") );
    wxStaticBoxSizer *item1 = new wxStaticBoxSizer( item2, wxVERTICAL );

    MyTextCtrl *item3 = new MyTextCtrl( parent, ID_TEXTCTRL1, wxT(""), wxDefaultPosition, wxSize(180,-1), 0 );
    item1->Add( item3, 0, wxALIGN_CENTRE|wxALL, 10 );

    MyTextCtrl *item4 = new MyTextCtrl( parent, ID_TEXTCTRL2, wxT(""), wxDefaultPosition, wxSize(180,-1), 0 );
    item1->Add( item4, 0, wxALIGN_CENTRE|wxALL, 10 );

    item0->Add( item1, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxStaticLine *item5 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item5, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item6 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item7 = new wxButton( parent, wxID_OK, wxT("OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item6->Add( item7, 0, wxALIGN_CENTRE|wxLEFT|wxRIGHT|wxBOTTOM, 5 );

    wxButton *item8 = new wxButton( parent, ID_TEST, wxT("Test"), wxDefaultPosition, wxDefaultSize, 0 );
    item8->SetToolTip( wxT("Copy text from first to second control") );
    item6->Add( item8, 0, wxALIGN_CENTRE|wxLEFT|wxRIGHT|wxBOTTOM, 5 );

    item0->Add( item6, 0, wxALIGN_CENTRE|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetAutoLayout( TRUE );
        parent->SetSizer( item0 );
        if (call_fit)
        {
            item0->Fit( parent );
            item0->SetSizeHints( parent );
        }
    }
    
    return item0;
}

// Implement menubar functions

// Implement toolbar functions

// Implement bitmap functions


// End of generated file
