# -*- coding: iso-8859-15 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: rad.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid

# Window functions

ID_TEXT = 10000
ID_MY_NUMBER = 10001
ID_MY_TEXT = 10002
ID_LINE = 10003

def MyDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item2 = wx.StaticBox( parent, -1, "Controls will remember their values" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )
    
    item3 = wx.FlexGridSizer( 0, 2, 0, 0 )
    item3.AddGrowableCol( 0 )
    item3.AddGrowableCol( 1 )
    
    item4 = wx.StaticText( parent, ID_TEXT, "wxSpinCtrl:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.SetName( "TestName" )
    item3.Add( item4, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item5 = wx.SpinCtrl( parent, ID_MY_NUMBER, "0", wx.DefaultPosition, [130,-1], wx.SP_ARROW_KEYS|wx.SP_WRAP, 0, 100, 0 )
    item3.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item6 = wx.StaticText( parent, ID_TEXT, "wxTextCtrl:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item6, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item7 = wx.TextCtrl( parent, ID_MY_TEXT, "", wx.DefaultPosition, [130,-1], 0 )
    item3.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item1.Add( item3, 1, wx.GROW|wx.ALL, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item8 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [300,-1], wx.LI_HORIZONTAL )
    item0.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item9 = wx.Button( parent, wx.ID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item0.Add( item9, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


# End of generated file
