#-----------------------------------------------------------------------------
# Perl source generated by wxDesigner from file: rad.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

use Wx;
use strict;

use Wx qw( wxDefaultSize wxDefaultPosition wxID_OK wxID_CANCEL wxID_YES wxID_EXIT wxID_ABOUT );
use Wx qw( wxVERTICAL wxHORIZONTAL wxALL wxLEFT wxRIGHT wxTOP wxBOTTOM wxCENTRE wxGROW wxADJUST_MINSIZE );
use Wx qw( wxALIGN_RIGHT wxALIGN_BOTTOM wxALIGN_CENTER wxALIGN_CENTER_VERTICAL wxALIGN_CENTER_HORIZONTAL );
use Wx qw( wxSP_ARROW_KEYS wxSP_WRAP wxLI_HORIZONTAL );

# Bitmap functions

use Wx qw( wxNullBitmap wxBITMAP_TYPE_PNG );

# Window functions

use vars qw($ID_TEXT); $ID_TEXT = 10000;
use vars qw($ID_MY_NUMBER); $ID_MY_NUMBER = 10001;
use vars qw($ID_MY_TEXT); $ID_MY_TEXT = 10002;
use vars qw($ID_LINE); $ID_LINE = 10003;

sub MyDialogFunc {
    my( $item0 ) = Wx::BoxSizer->new( wxVERTICAL );
    
    my( $item2 ) = Wx::StaticBox->new( $_[0], -1, "Controls will remember their values" );
    my( $item1 ) = Wx::StaticBoxSizer->new( $item2, wxVERTICAL );
    
    my( $item3 ) = Wx::FlexGridSizer->new( 0, 2, 0, 0 );
    $item3->AddGrowableCol( 0 );
    $item3->AddGrowableCol( 1 );
    
    my( $item4 ) = Wx::StaticText->new( $_[0], $main::ID_TEXT, "wxSpinCtrl:", wxDefaultPosition, wxDefaultSize, 0 );
    $item4->SetName( "TestName" );
    $item3->AddWindow( $item4, 0, wxALIGN_CENTER|wxALL, 5 );

    my( $item5 ) = Wx::SpinCtrl->new( $_[0], $main::ID_MY_NUMBER, "0", wxDefaultPosition, [130,-1], wxSP_ARROW_KEYS|wxSP_WRAP, 0, 100, 0 );
    $item3->AddWindow( $item5, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item6 ) = Wx::StaticText->new( $_[0], $main::ID_TEXT, "wxTextCtrl:", wxDefaultPosition, wxDefaultSize, 0 );
    $item3->AddWindow( $item6, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item7 ) = Wx::TextCtrl->new( $_[0], $main::ID_MY_TEXT, "", wxDefaultPosition, [130,-1], 0 );
    $item3->AddWindow( $item7, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    $item1->Add( $item3, 1, wxGROW|wxALL, 5 );

    $item0->Add( $item1, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item8 ) = Wx::StaticLine->new( $_[0], $main::ID_LINE, wxDefaultPosition, [300,-1], wxLI_HORIZONTAL );
    $item0->AddWindow( $item8, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item9 ) = Wx::Button->new( $_[0], wxID_OK, "OK", wxDefaultPosition, wxDefaultSize, 0 );
    $item0->AddWindow( $item9, 0, wxALIGN_CENTER|wxALL, 5 );

    my( $set_size ) = @_ >= 3 ? $_[2] : 1;
    my( $call_fit ) = @_ >= 2 ? $_[1] : 1;
    if( $set_size == 1 ) {
         $_[0]->SetSizer( $item0 );
         
         if( $call_fit == 1 ) {
             $item0->SetSizeHints( $_[0] );
         }
    }
    
    $item0;
}

# Menu bar functions


# Toolbar functions


# End of generated file
