# -*- coding: iso-8859-1 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: grid.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxWindows' modules
import wx
import wx.grid

# Custom source
from grid_derived import *

# Window functions

ID_GRID = 10000
ID_LINE = 10001
ID_TEXT = 10002
wxID_OK = 5100

def MyDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item2 = wx.StaticBox( parent, -1, "Text" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )
    
    item3 = MyGrid( parent, ID_GRID, wx.DefaultPosition, [450,200], wx.WANTS_CHARS )
    item3.CreateGrid( 10, 4, wx.grid.Grid.SelectCells )
    item1.Add( item3, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item4 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item1.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item5 = wx.StaticText( parent, ID_TEXT, "Right-click on a cell!", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item5, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item6 = wx.BoxSizer( wx.HORIZONTAL )
    
    item7 = wx.Button( parent, wxID_OK, "Leave", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item7, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item6, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

ID_QUIT = 10003
ID_MENU = 10004

def MyMenuBarFunc():
    item0 = wx.MenuBar()
    
    item1 = wx.Menu()
    item1.Append( ID_GRID, "MyGrid\tF2", "" )
    item1.Append( ID_QUIT, "Quit", "" )
    item0.Append( item1, "File" )
    
    return item0

# Toolbar functions

# Bitmap functions


# End of generated file
