# -*- coding: UTF-8 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: INCAR.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid
import wx.animate

# Window functions

ID_SPLITTER = 10000

def MyDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.HORIZONTAL )
    
    item1 = wx.SplitterWindow( parent, ID_SPLITTER, wx.DefaultPosition, wx.DefaultSize, wx.SP_BORDER|wx.SP_3D|wx.CLIP_CHILDREN )
    item2 = wx.Panel( item1, -1 )
    LeftDialogFunc( item2, False, True )
    item1.Initialize( item2 )
    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_COLLPANE = 10001
ID_NOTEBOOK = 10002

def LeftDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item1 = wx.CollapsiblePane( parent, ID_COLLPANE, "Tags Classified by Function", wx.DefaultPosition, [10,10], wx.CP_NO_TLW_RESIZE )
    oldparent = parent
    parent = item1.GetPane()
    
    item2 = wx.BoxSizer( wx.VERTICAL )
    
    item4 = wx.Notebook( parent, ID_NOTEBOOK, wx.DefaultPosition, [200,160], 0 )
    item3 = item4
    
    item5 = wx.Panel( item4, -1 )
    item4.AddPage( item5, "Output Control" )

    item6 = wx.Panel( item4, -1 )
    item4.AddPage( item6, "Ion Related" )

    item2.Add( item3, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    parent.SetSizer( item2 )
    parent = oldparent
    
    item0.Add( item1, 0, wx.ALL, 15 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


# End of generated file
