# -*- coding: UTF-8 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: Derived.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid
import wx.animate

# Custom source
from derived2 import *

# Window functions

ID_TEXTCTRL1 = 10000
ID_TEXTCTRL2 = 10001
ID_LINE = 10002
ID_BUTTON_TEST = 10003

def MyDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item2 = wx.StaticBox( parent, -1, "Special Text Ctrl" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )
    
    item3 = Derived_ctrl( parent, ID_TEXTCTRL1, "", wx.DefaultPosition, [180,-1], 0|wx.EXPAND )
    item1.Add( item3, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item4 = Derived_ctrl( parent, ID_TEXTCTRL2, "", wx.DefaultPosition, [180,-1], 0|wx.GROW )
    item1.Add( item4, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item5 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [180,-1], wx.LI_HORIZONTAL )
    item1.Add( item5, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item6 = wx.BoxSizer( wx.HORIZONTAL )
    
    item7 = wx.Button( parent, wx.ID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item7, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item8 = wx.Button( parent, ID_BUTTON_TEST, "TEST", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.SetToolTip( wx.ToolTip("Copy Text from Text Ctrl above") )
    item6.Add( item8, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item6, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

ID_MENU_TEST = 10004
ID_MENU = 10005

def MyMenuBarFunc():
    item0 = wx.MenuBar()
    
    item1 = wx.Menu()
    item1.Append( ID_MENU_TEST, "Start Test Dialog\tCtrl-S", "Start Test Dialog" )
    item1.Append( wx.ID_ABOUT, "About", "" )
    item1.Append( wx.ID_EXIT, "Quit", "" )
    item0.Append( item1, "File" )
    
    return item0

# Toolbar functions


def MyToolBarFunc( parent ):
    parent.SetMargins( [2,2] )
    
    
    parent.Realize()

# Bitmap functions


# End of generated file
