# -*- coding: iso-8859-15 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: dynamic.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxWindows' modules
import wx
import wx.grid

# Window functions

ID_TEXT = 10000
ID_CHOICE = 10001
ID_LINE = 10002

def MyDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item2 = wx.StaticBox( parent, -1, "Text" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )
    parent.my_sizer = item1
    
    item3 = wx.StaticText( parent, ID_TEXT, "This demonstrates a dynamic interface", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item3, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item4 = wx.Choice( parent, ID_CHOICE, wx.DefaultPosition, [160,-1], 
        ["Page 1","Page 2"] , 0 )
    item1.Add( item4, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item5 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item0.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item6 = wx.Button( parent, wx.ID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item0.Add( item6, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_TEXT1 = 10003
ID_TEXTCTRL1 = 10004
ID_TEXT2 = 10005
ID_TEXTCTRL2 = 10006

def MyPageOneFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item1 = wx.StaticText( parent, ID_TEXT1, "Text input:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item2 = wx.TextCtrl( parent, ID_TEXTCTRL1, "", wx.DefaultPosition, [140,-1], 0 )
    item0.Add( item2, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item3 = wx.StaticText( parent, ID_TEXT2, "More text:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item0.Add( item3, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item4 = wx.TextCtrl( parent, ID_TEXTCTRL2, "", wx.DefaultPosition, [140,-1], 0 )
    item0.Add( item4, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_LISTBOX = 10007

def MyPageTwoFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item1 = wx.ListBox( parent, ID_LISTBOX, wx.DefaultPosition, [160,100], 
        ["Item 1","Item 2","Item 3","Item 4"] , wx.LB_SINGLE|wx.LB_ALWAYS_SB )
    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

ID_TEST = 10008
ID_MENU = 10009

def MyMenuBarFunc():
    item0 = wx.MenuBar()
    
    item1 = wx.Menu()
    item1.Append( wx.ID_ABOUT, "About", "" )
    item1.Append( ID_TEST, "Test...", "" )
    item1.Append( wx.ID_EXIT, "Quit", "" )
    item0.Append( item1, "File" )
    
    return item0

# Toolbar functions

# Bitmap functions


# End of generated file
