//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: dynamic.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_dynamic_H__
#define __WDR_dynamic_H__

#if defined(__GNUG__) && !defined(__APPLE__)
    #pragma interface "dynamic_wdr.h"
#endif

// Include wxWindows' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

extern wxSizer *my_sizer;
const int ID_TEXT = 10000;
const int ID_CHOICE = 10001;
const int ID_LINE = 10002;
wxSizer *MyDialogFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXT1 = 10003;
const int ID_TEXTCTRL1 = 10004;
const int ID_TEXT2 = 10005;
const int ID_TEXTCTRL2 = 10006;
wxSizer *MyPageOneFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_LISTBOX = 10007;
wxSizer *MyPageTwoFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

const int ID_MENU = 10008;
const int ID_TEST = 10009;
wxMenuBar *MyMenuBarFunc();

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
