//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: scrolled.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_scrolled_H__
#define __WDR_scrolled_H__

#ifdef __GNUG__
    #pragma interface "scrolled_wdr.h"
#endif

// Include wxWindows' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>

// Declare window functions

#define ID_SCROLLED 10000
#define ID_PANEL 10001
#define ID_LINE 10002
wxSizer *MyDialogFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

#define ID_MENU 10003
#define ID_QUIT 10004
wxMenuBar *MyMenuBarFunc();

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
