#-----------------------------------------------------------------------------
# Perl source generated by wxDesigner from file: scrolled.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

use Wx;
use strict;

# Custom source
do 'scrolled_derived.pl';
die $@ if $@;

use Wx qw( wxDefaultSize wxDefaultPosition wxID_OK wxID_CANCEL wxID_YES );
use Wx qw( wxVERTICAL wxHORIZONTAL wxALL wxLEFT wxRIGHT wxTOP wxBOTTOM wxCENTRE wxGROW );
use Wx qw( wxALIGN_RIGHT wxALIGN_BOTTOM wxALIGN_CENTRE wxALIGN_CENTER_VERTICAL wxALIGN_CENTER_HORIZONTAL );
use Wx qw( wxHSCROLL wxVSCROLL wxSUNKEN_BORDER wxLI_HORIZONTAL );

# Window functions

use vars qw($ID_SCROLLED); $ID_SCROLLED = 10000;
use vars qw($ID_PANEL); $ID_PANEL = 10001;
use vars qw($ID_LINE); $ID_LINE = 10002;

sub MyDialogFunc {
    my( $item0 ) = Wx::BoxSizer->new( wxVERTICAL );
    
    my( $item1 ) = MyScrolledWindow->new( $_[0], $main::ID_SCROLLED, wxDefaultPosition, [390,140], wxHSCROLL|wxVSCROLL|wxSUNKEN_BORDER );
    $item1->SetScrollbars( 10, 10, 20, 100, 0, 0 );
    $item0->AddWindow( $item1, 0, wxALIGN_CENTRE|wxALL, 5 );

    my( $item2 ) = Wx::Panel->new( $_[0], $main::ID_PANEL, wxDefaultPosition, [390,130], wxSUNKEN_BORDER );
    $item0->AddWindow( $item2, 0, wxALIGN_CENTRE|wxALL, 5 );

    my( $item3 ) = Wx::StaticLine->new( $_[0], $main::ID_LINE, wxDefaultPosition, [20,-1], wxLI_HORIZONTAL );
    $item0->AddWindow( $item3, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item4 ) = Wx::BoxSizer->new( wxHORIZONTAL );
    
    my( $item5 ) = Wx::Button->new( $_[0], wxID_OK, "OK", wxDefaultPosition, wxDefaultSize, 0 );
    $item4->AddWindow( $item5, 0, wxALIGN_CENTRE|wxLEFT|wxRIGHT|wxBOTTOM, 5 );

    $item0->Add( $item4, 0, wxALIGN_CENTRE|wxALL, 5 );

    my( $set_size ) = @_ >= 3 ? $_[2] : 1;
    my( $call_fit ) = @_ >= 2 ? $_[1] : 1;
    if( $set_size == 1 ) {
         $_[0]->SetAutoLayout( 1 );
         $_[0]->SetSizer( $item0 );
         
         if( $call_fit == 1 ) {
             $item0->Fit( $_[0] );
             $item0->SetSizeHints( $_[0] );
         }
    }
    
    $item0;
}

# Menu bar functions

use vars qw($ID_MENU); $ID_MENU = 10003;
use vars qw($ID_QUIT); $ID_QUIT = 10004;

sub MyMenuBarFunc {
    my( $item0 ) = Wx::MenuBar->new();
    
    my( $item1 ) = Wx::Menu->new();
    $item1->Append( $main::ID_SCROLLED, "Scrolled\tF2", "" );
    $item1->Append( $main::ID_QUIT, "Quit", "" );
    $item0->Append( $item1, "File" );
    
    $item0;
}

# Bitmap functions

use Wx qw( wxNullBitmap wxBITMAP_TYPE_PNG );


# Toolbar functions


# End of generated file
