# -*- coding: iso-8859-1 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: scrolled.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxWindows' modules
from wxPython.wx import *
from wxPython.grid import *

# Custom source
from scrolled_derived import *

# Window functions

ID_SCROLLED = 10000
ID_PANEL = 10001
ID_LINE = 10002

def MyDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wxBoxSizer( wxVERTICAL )
    
    item1 = MyScrolledWindow( parent, ID_SCROLLED, wxDefaultPosition, wxSize(390,140), wxHSCROLL|wxVSCROLL|wxSUNKEN_BORDER )
    item1.SetScrollbars( 10, 10, 20, 100, 0, 0 )
    item0.Add( item1, 0, wxALIGN_CENTER|wxALL, 5 )

    item2 = wxPanel( parent, ID_PANEL, wxDefaultPosition, wxSize(390,130), wxSUNKEN_BORDER )
    item0.Add( item2, 0, wxALIGN_CENTER|wxALL, 5 )

    item3 = wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL )
    item0.Add( item3, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item4 = wxBoxSizer( wxHORIZONTAL )
    
    item5 = wxButton( parent, wxID_OK, "OK", wxDefaultPosition, wxDefaultSize, 0 )
    item4.Add( item5, 0, wxALIGN_CENTER|wxLEFT|wxRIGHT|wxBOTTOM, 5 )

    item0.Add( item4, 0, wxALIGN_CENTER|wxALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

ID_QUIT = 10003
ID_MENU = 10004

def MyMenuBarFunc():
    item0 = wxMenuBar()
    
    item1 = wxMenu()
    item1.Append( ID_SCROLLED, "Scrolled\tF2", "" )
    item1.Append( ID_QUIT, "Quit", "" )
    item0.Append( item1, "File" )
    
    return item0

# Toolbar functions

# Bitmap functions


# End of generated file
