//------------------------------------------------------------------------------
// Source code generated by wxDesigner from file: scrolled.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifdef __GNUG__
    #pragma implementation "scrolled_wdr.h"
#endif

// For compilers that support precompilation
#include "wx/wxprec.h"

#ifdef __BORLANDC__
    #pragma hdrstop
#endif

// Include private header
#include "scrolled_wdr.h"


// Custom source
#include "scrolled.h"

// Implement window functions

wxSizer *MyDialogFunc( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    MyScrolledWindow *item1 = new MyScrolledWindow( parent, ID_SCROLLED, wxDefaultPosition, wxSize(390,140), wxHSCROLL|wxVSCROLL|wxSUNKEN_BORDER );
    item1->SetScrollbars( 10, 10, 20, 100, 0, 0 );
    item0->Add( item1, 0, wxALIGN_CENTRE|wxALL, 5 );

    wxPanel *item2 = new wxPanel( parent, ID_PANEL, wxDefaultPosition, wxSize(390,130), wxSUNKEN_BORDER );
    item0->Add( item2, 0, wxALIGN_CENTRE|wxALL, 5 );

    wxStaticLine *item3 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item3, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item4 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item5 = new wxButton( parent, wxID_OK, wxT("OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item4->Add( item5, 0, wxALIGN_CENTRE|wxLEFT|wxRIGHT|wxBOTTOM, 5 );

    item0->Add( item4, 0, wxALIGN_CENTRE|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetAutoLayout( TRUE );
        parent->SetSizer( item0 );
        if (call_fit)
        {
            item0->Fit( parent );
            item0->SetSizeHints( parent );
        }
    }
    
    return item0;
}

// Implement menubar functions

wxMenuBar *MyMenuBarFunc()
{
    wxMenuBar *item0 = new wxMenuBar;
    
    wxMenu* item1 = new wxMenu;
    item1->Append( ID_SCROLLED, wxT("Scrolled\tF2"), wxT("") );
    item1->Append( ID_QUIT, wxT("Quit"), wxT("") );
    item0->Append( item1, wxT("File") );
    
    return item0;
}

// Implement toolbar functions

// Implement bitmap functions


// End of generated file
