# -*- coding: iso-8859-15 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: toolbar.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid

# Window functions

# Menubar functions

ID_MENU = 10000

def MyMenuBarFunc():
    item0 = wx.MenuBar()
    
    item1 = wx.Menu()
    item1.Append( wx.ID_ABOUT, "About\tAlt-A", "" )
    item1.Append( wx.ID_SAVE, "Save\tAlt-S", "" )
    item1.Append( wx.ID_EXIT, "Quit\tAlt-Q", "" )
    item0.Append( item1, "File" )
    
    return item0

# Toolbar functions

ID_OPEN = 10001
ID_CUT = 10002
ID_COPY = 10003
ID_PASTE = 10004
ID_FONT = 10005

def MyToolBarFunc( parent ):
    parent.SetMargins( [2,2] )
    
    parent.AddLabelTool( wx.ID_EXIT, "Exit", MyBitmapsFunc( 0 ), wx.NullBitmap, wx.ITEM_NORMAL, "Exit app", "Exit application" )
    parent.AddSeparator()
    parent.AddLabelTool( ID_OPEN, "", MyBitmapsFunc( 1 ), wx.NullBitmap, wx.ITEM_NORMAL, "Open", "Open document" )
    parent.AddLabelTool( wx.ID_SAVE, "", MyBitmapsFunc( 5 ), wx.NullBitmap, wx.ITEM_NORMAL, "Save", "Save document" )
    parent.AddSeparator()
    parent.AddLabelTool( ID_CUT, "Cut", MyBitmapsFunc( 2 ), wx.NullBitmap, wx.ITEM_NORMAL, "Cut", "Move to clipboard" )
    parent.EnableTool( ID_CUT, False )
    parent.AddLabelTool( ID_COPY, "Copy", MyBitmapsFunc( 3 ), wx.NullBitmap, wx.ITEM_NORMAL, "Copy", "Copy to clipboard" )
    parent.EnableTool( ID_COPY, False )
    parent.AddLabelTool( ID_PASTE, "Paste", MyBitmapsFunc( 4 ), wx.NullBitmap, wx.ITEM_CHECK, "Paste", "Paste from clipboard" )
    parent.ToggleTool( ID_PASTE, True )
    parent.AddSeparator()
    item2 = wx.ComboBox( parent, ID_FONT, "", wx.DefaultPosition, [150,-1], 
        ["Times New Roman","Arial","Courier"] , wx.CB_DROPDOWN )
    item2.SetToolTip( wx.ToolTip("This is a toolbar control") )
    parent.AddControl( item2 )
    
    parent.Realize()

# Bitmap functions


def MyBitmapsFunc( index ):
    if index == 0:
        return wx.Image( "toolbar_wdr/MyBitmapsFunc_0.png", wx.BITMAP_TYPE_PNG ).ConvertToBitmap()
    if index == 1:
        return wx.Image( "toolbar_wdr/MyBitmapsFunc_1.png", wx.BITMAP_TYPE_PNG ).ConvertToBitmap()
    if index == 2:
        return wx.Image( "toolbar_wdr/MyBitmapsFunc_2.png", wx.BITMAP_TYPE_PNG ).ConvertToBitmap()
    if index == 3:
        return wx.Image( "toolbar_wdr/MyBitmapsFunc_3.png", wx.BITMAP_TYPE_PNG ).ConvertToBitmap()
    if index == 4:
        return wx.Image( "toolbar_wdr/MyBitmapsFunc_4.png", wx.BITMAP_TYPE_PNG ).ConvertToBitmap()
    if index == 5:
        return wx.Image( "toolbar_wdr/MyBitmapsFunc_5.png", wx.BITMAP_TYPE_PNG ).ConvertToBitmap()
    return wx.NullBitmap

# End of generated file
