# -*- coding: iso-8859-15 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: notebook.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid

# Window functions

ID_TEXTCTRL = 10000

def PageOneFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item1 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [200,-1], 0 )
    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 20 )

    item2 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [200,90], wx.TE_MULTILINE )
    item0.Add( item2, 0, wx.ALIGN_CENTER|wx.ALL, 20 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_CHECKBOX = 10001
ID_BUTTON = 10002

def PageTwoFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item2 = wx.StaticBox( parent, -1, "Checks" )
    item1 = wx.StaticBoxSizer( item2, wx.HORIZONTAL )
    
    item3 = wx.CheckBox( parent, ID_CHECKBOX, "Check", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item3, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item4 = wx.CheckBox( parent, ID_CHECKBOX, "Check", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item4, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item5 = wx.CheckBox( parent, ID_CHECKBOX, "Check", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item5, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item7 = wx.StaticBox( parent, -1, "Buttons" )
    item6 = wx.StaticBoxSizer( item7, wx.VERTICAL )
    
    item8 = wx.Button( parent, ID_BUTTON, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item8, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item9 = wx.Button( parent, ID_BUTTON, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item9, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item10 = wx.Button( parent, ID_BUTTON, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_NOTEBOOK = 10003
ID_LINE = 10004

def NotebookFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item2 = wx.Notebook( parent, ID_NOTEBOOK, wx.DefaultPosition, [200,160], 0 )
    if wx.VERSION >= (2,5,2):
        item1 = item2
    else:
        item1 = wx.NotebookSizer( item2 )
    
    item3 = wx.Panel( item2, -1 )
    PageOneFunc(item3, False)
    item2.AddPage( item3, "Page 1" )

    item4 = wx.Panel( item2, -1 )
    PageTwoFunc(item4, False)
    item2.AddPage( item4, "Page 2" )

    item5 = wx.Panel( item2, -1 )
    item2.AddPage( item5, "Page 3" )

    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item6 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item0.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item7 = wx.BoxSizer( wx.HORIZONTAL )
    
    item8 = wx.Button( parent, wx.ID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.SetDefault()
    item7.Add( item8, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item9 = wx.Button( parent, wx.ID_CANCEL, "Cancel", wx.DefaultPosition, wx.DefaultSize, 0 )
    item7.Add( item9, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item7, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


# End of generated file
