# -*- coding: UTF-8 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: Dynamic_exec.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid
import wx.animate

# Window functions

ID_TEXT_STATIC = 10000
ID_CHOICE = 10001
ID_LINE = 10002

def TestDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item2 = wx.StaticBox( parent, -1, "Text" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )
    
    item3 = wx.StaticText( parent, ID_TEXT_STATIC, "This demonstrates a dynamic interface", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_CENTRE )
    item1.Add( item3, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item4 = wx.Choice( parent, ID_CHOICE, wx.DefaultPosition, [100,-1], 
        ["Page1","Page2"] , 0 )
    item1.Add( item4, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item5 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [120,-1], wx.LI_HORIZONTAL )
    item0.Add( item5, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item6 = wx.Button( parent, wx.ID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item0.Add( item6, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_TEXT_PAGE1 = 10003
ID_TEXTCTRL = 10004

def PageDialogFunc1( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item1 = wx.StaticText( parent, ID_TEXT_PAGE1, 
        "Text Input:\n"
        "",
        wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_CENTRE )
    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item2 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,-1], 0 )
    item0.Add( item2, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item3 = wx.StaticText( parent, ID_TEXT_PAGE1, "More text", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_CENTRE )
    item0.Add( item3, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item4 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,-1], 0 )
    item0.Add( item4, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_LISTBOX = 10005

def PageDialogFunc2( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item1 = wx.ListBox( parent, ID_LISTBOX, wx.DefaultPosition, [80,100], 
        ["ListItem1","ListItem2",""] , wx.LB_SINGLE|wx.LB_ALWAYS_SB )
    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

ID_MENU_Test = 10006
ID_MENU = 10007

def FileMenuBarFunc():
    item0 = wx.MenuBar()
    
    item1 = wx.Menu()
    item1.Append( wx.ID_ABOUT, "About", "" )
    item1.Append( ID_MENU_Test, "Test...", "Start the test" )
    item1.Append( wx.ID_EXIT, "Quit", "" )
    item0.Append( item1, "File" )
    
    return item0

# Toolbar functions

# Bitmap functions


# End of generated file
