# -*- coding: UTF-8 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: grid_sizer1.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid
import wx.animate

# Window functions

ID_BUTTON_ITEM1 = 10000
ID_BUTTON_ITEM2 = 10001
ID_BUTTON_ITEM3 = 10002
ID_BUTTON_ITEM4 = 10003

def MyDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.GridSizer( 0, 2, 2, 2 )
    
    item1 = wx.Button( parent, ID_BUTTON_ITEM1, "Item1", wx.DefaultPosition, wx.DefaultSize, 0 )
    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item2 = wx.Button( parent, ID_BUTTON_ITEM2, "Item2", wx.DefaultPosition, wx.DefaultSize, 0 )
    item0.Add( item2, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item3 = wx.Button( parent, ID_BUTTON_ITEM3, "Item3", wx.DefaultPosition, wx.DefaultSize, 0 )
    item0.Add( item3, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item4 = wx.Button( parent, ID_BUTTON_ITEM4, "Item4", wx.DefaultPosition, wx.DefaultSize, 0 )
    item0.Add( item4, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

ID_MENU = 10004
ID_SUBMENU_ITEM1 = 10005
ID_SUBMENU_ITEM2 = 10006
ID_SUBMENU_ITEM3 = 10007
ID_FILE_SUBMENU = 10008
ID_RADIO1 = 10009
ID_RADIO2 = 10010

def MyMenuBarFunc():
    item0 = wx.MenuBar()
    
    item1 = wx.Menu()
    item2 = wx.MenuItem( item1, ID_MENU, "&About", "" )
    item2.SetBitmap( MyBitmapsFunc( 0 ) )
    item1.AppendItem( item2 )
    item1.AppendSeparator()
    
    item3 = wx.Menu()
    item3.Append( ID_SUBMENU_ITEM1, "Item1", "" )
    item3.Append( ID_SUBMENU_ITEM2, "Item2", "" )
    item3.Append( ID_SUBMENU_ITEM3, "Item3", "" )
    item1.AppendMenu( ID_FILE_SUBMENU, "Submenu", item3 )

    
    item4 = wx.Menu()
    item4.Append( ID_RADIO1, "Radio1", "", wx.ITEM_RADIO )
    item4.Append( ID_RADIO2, "Radio2", "", wx.ITEM_RADIO )
    item1.AppendMenu( ID_MENU, "Radio Submenu", item4 )

    item0.Append( item1, "&File" )
    
    return item0

# Toolbar functions

# Bitmap functions


def MyBitmapsFunc( index ):
    if index == 0:
        return wx.Image( "grid_sizer1_wdr/MyBitmapsFunc_0.png", wx.BITMAP_TYPE_PNG ).ConvertToBitmap()
    if index == 1:
        return wx.Image( "grid_sizer1_wdr/MyBitmapsFunc_1.png", wx.BITMAP_TYPE_PNG ).ConvertToBitmap()
    return wx.NullBitmap

# End of generated file
