# -*- coding: iso-8859-15 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: menu.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxWindows' modules
import wx
import wx.grid

# Window functions

# Menubar functions

ID_MENU = 10000
ID_TEST1 = 10001
ID_TEST2 = 10002
ID_TEST3 = 10003
ID_RADIO = 10004

def MyMenuBarFunc():
    item0 = wx.MenuBar()
    
    item1 = wx.Menu()
    item2 = wx.MenuItem( item1, wx.ID_ABOUT, "&About...", "Helptext for About" )
    item2.SetBitmap( MyBitmapsFunc( 0 ) )
    item1.AppendItem( item2 )
    item1.AppendSeparator()
    
    item3 = wx.Menu()
    item3.Append( ID_TEST1, "Test 1\tF1", "", wx.ITEM_CHECK )
    item3.Append( ID_TEST2, "Test 2\tF2", "", wx.ITEM_CHECK )
    item3.Append( ID_TEST3, "Test 3\tF3", "", wx.ITEM_CHECK )
    item1.AppendMenu( ID_MENU, "Submenu", item3 )

    
    item4 = wx.Menu()
    item4.Append( ID_RADIO, "Radio 1", "", wx.ITEM_RADIO )
    item4.Append( ID_RADIO, "Radio 2", "", wx.ITEM_RADIO )
    item1.AppendMenu( ID_MENU, "Radio submenu", item4 )

    item1.AppendSeparator()
    item1.Append( wx.ID_EXIT, "&Quit\tAlt-Q", "Helptext for Quit" )
    item0.Append( item1, "&File" )
    
    return item0

# Toolbar functions

# Bitmap functions


def MyBitmapsFunc( index ):
    if index == 0:
        return wx.Image( "menu_wdr/MyBitmapsFunc_0.png", wx.BITMAP_TYPE_PNG ).ConvertToBitmap()
    return wx.NullBitmap

# End of generated file
