#-----------------------------------------------------------------------------
# Perl source generated by wxDesigner from file: menu.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

use Wx;
use strict;

use Wx qw( wxDefaultSize wxDefaultPosition wxID_OK wxID_CANCEL wxID_YES wxID_EXIT wxID_ABOUT );
use Wx qw( wxVERTICAL wxHORIZONTAL wxALL wxLEFT wxRIGHT wxTOP wxBOTTOM wxCENTRE wxGROW wxADJUST_MINSIZE );
use Wx qw( wxALIGN_RIGHT wxALIGN_BOTTOM wxALIGN_CENTER wxALIGN_CENTER_VERTICAL wxALIGN_CENTER_HORIZONTAL );


# Bitmap functions

use Wx qw( wxNullBitmap wxBITMAP_TYPE_PNG );


sub MyBitmapsFunc {
    if ($_[0] == 0) {
        my( $bitmap ) = Wx::Bitmap->new( "menu_wdr/MyBitmapsFunc_0.png", wxBITMAP_TYPE_PNG );
        return $bitmap;
    }
    wxNullBitmap;
}
# Window functions

# Menu bar functions

use vars qw($ID_MENU); $ID_MENU = 10000;
use vars qw($ID_TEST1); $ID_TEST1 = 10001;
use vars qw($ID_TEST2); $ID_TEST2 = 10002;
use vars qw($ID_TEST3); $ID_TEST3 = 10003;
use vars qw($ID_RADIO); $ID_RADIO = 10004;

sub MyMenuBarFunc {
    my( $item0 ) = Wx::MenuBar->new();
    
    my( $item1 ) = Wx::Menu->new();
    my( $item2 ) = Wx::MenuItem->new( $item1, wxID_ABOUT, "&About...", "Helptext for About" );
    $item2->SetBitmap( MyBitmapsFunc( 0 ) );
    $item1->Append( $item2 );
    $item1->AppendSeparator();
    
    my( $item3 ) = Wx::Menu->new();
    $item3->AppendCheckItem( $main::ID_TEST1, "Test 1\tF1", "" );
    $item3->AppendCheckItem( $main::ID_TEST2, "Test 2\tF2", "" );
    $item3->AppendCheckItem( $main::ID_TEST3, "Test 3\tF3", "" );
    $item1->Append( $main::ID_MENU, "Submenu", $item3 );

    
    my( $item4 ) = Wx::Menu->new();
    $item4->AppendRadioItem( $main::ID_RADIO, "Radio 1", "" );
    $item4->AppendRadioItem( $main::ID_RADIO, "Radio 2", "" );
    $item1->Append( $main::ID_MENU, "Radio submenu", $item4 );

    $item1->AppendSeparator();
    $item1->AppendString( wxID_EXIT, "&Quit\tAlt-Q", "Helptext for Quit" );
    $item0->Append( $item1, "&File" );
    
    $item0;
}


# Toolbar functions


# End of generated file
