//------------------------------------------------------------------------------
// Source code generated by wxDesigner from file: menu.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifdef __GNUG__
    #pragma implementation "menu_wdr.h"
#endif

// For compilers that support precompilation
#include "wx/wxprec.h"

#ifdef __BORLANDC__
    #pragma hdrstop
#endif

// Include private header
#include "menu_wdr.h"


// Euro sign hack of the year
#if wxUSE_UNICODE
    #define __WDR_EURO__ wxT("\u20ac")
#else
    #if defined(__WXMAC__)
        #define __WDR_EURO__ wxT("\xdb")
    #elif defined(__WXMSW__)
        #define __WDR_EURO__ wxT("\x80")
    #else
        #define __WDR_EURO__ wxT("\xa4")
    #endif
#endif

// Implement window functions

// Implement menubar functions

wxMenuBar *MyMenuBarFunc()
{
    wxMenuBar *item0 = new wxMenuBar;
    
    wxMenu* item1 = new wxMenu;
    wxMenuItem *item2 = new wxMenuItem( item1, wxID_ABOUT, wxT("&About..."), wxT("Helptext for About") );
    item2->SetBitmap( MyBitmapsFunc( 0 ) );
    item1->Append( item2 );
    item1->AppendSeparator();
    
    wxMenu* item3 = new wxMenu;
    item3->Append( ID_TEST1, wxT("Test 1\tF1"), wxT(""), wxITEM_CHECK );
    item3->Append( ID_TEST2, wxT("Test 2\tF2"), wxT(""), wxITEM_CHECK );
    item3->Append( ID_TEST3, wxT("Test 3\tF3"), wxT(""), wxITEM_CHECK );
    item1->Append( ID_MENU, wxT("Submenu"), item3 );

    
    wxMenu* item4 = new wxMenu;
    item4->Append( ID_RADIO, wxT("Radio 1"), wxT(""), wxITEM_RADIO );
    item4->Append( ID_RADIO, wxT("Radio 2"), wxT(""), wxITEM_RADIO );
    item1->Append( ID_MENU, wxT("Radio submenu"), item4 );

    item1->AppendSeparator();
    item1->Append( wxID_EXIT, wxT("&Quit\tAlt-Q"), wxT("Helptext for Quit") );
    item0->Append( item1, wxT("&File") );
    
    return item0;
}

// Implement toolbar functions

// Implement bitmap functions

wxBitmap MyBitmapsFunc( size_t index )
{
    if (index == 0)
    {
        /* XPM */
        static const char *xpm_data[] = {
        /* columns rows colors chars-per-pixel */
        "16 15 2 1",
        "  c None",
        "b c #0000FF",
        /* pixels */
        "                ",
        "                ",
        "   bbbbbbb      ",
        "  bb     bb     ",
        "          b     ",
        "          b     ",
        "         bb     ",
        "     bbbbb      ",
        "    bb          ",
        "    b           ",
        "    bb          ",
        "     bbbbbbb    ",
        "                ",
        "          bbb   ",
        "          bbbb  "
        };
        wxBitmap bitmap( xpm_data );
        return bitmap;
    }
    return wxNullBitmap;
}


// End of generated file
