//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: menu.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_menu_H__
#define __WDR_menu_H__

#if defined(__GNUG__) && !defined(__APPLE__)
    #pragma interface "menu_wdr.h"
#endif

// Include wxWindows' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

// Declare menubar functions

const int ID_MENU = 10000;
const int ID_TEST1 = 10001;
const int ID_TEST2 = 10002;
const int ID_TEST3 = 10003;
const int ID_RADIO = 10004;
wxMenuBar *MyMenuBarFunc();

// Declare toolbar functions

// Declare bitmap functions

wxBitmap MyBitmapsFunc( size_t index );

#endif

// End of generated file
