//-----------------------------------------------------------------------------
// C# source generated by wxDesigner from file: menu.wdr
// Do not modify this file, all changes will be lost!
//-----------------------------------------------------------------------------

using System;
using System.Drawing;
using wx;

public class menuWdrClass
{
   // Window functions

    // Menubar functions

    public const int ID_MENU = 10000;
    public const int ID_TEST1 = 10001;
    public const int ID_TEST2 = 10002;
    public const int ID_TEST3 = 10003;
    public const int ID_RADIO = 10004;

    public static MenuBar MyMenuBarFunc()
    {
        MenuBar item0 = new MenuBar();
    
        Menu item1 = new Menu();
        item1.Append( (int)MenuIDs.wxID_ABOUT, "&About...", "Helptext for About" );
        item1.AppendSeparator();
    
        Menu item2 = new Menu();
        item2.Append( ID_TEST1, "Test 1\tF1", "", ItemKind.wxITEM_CHECK );
        item2.Append( ID_TEST2, "Test 2\tF2", "", ItemKind.wxITEM_CHECK );
        item2.Append( ID_TEST3, "Test 3\tF3", "", ItemKind.wxITEM_CHECK );
        item1.Append( ID_MENU, "Submenu", item2, "" );

    
        Menu item3 = new Menu();
        item3.Append( ID_RADIO, "Radio 1", "", ItemKind.wxITEM_RADIO );
        item3.Append( ID_RADIO, "Radio 2", "", ItemKind.wxITEM_RADIO );
        item1.Append( ID_MENU, "Radio submenu", item3, "" );

        item1.AppendSeparator();
        item1.Append( (int)MenuIDs.wxID_EXIT, "&Quit\tAlt-Q", "Helptext for Quit" );
        item0.Append( item1, "&File" );
        
        return item0;

    }
    // Toolbar functions

    // Bitmap functions

    
    public static wx.Bitmap MyBitmapsFunc( int index )
    {
        if (index == 0)
        {
             wx.Image image = new wx.Image( "menu_wdr/MyBitmapsFunc_0.png" );
             wx.Bitmap bitmap = new wx.Bitmap( image );
             return bitmap;
        }
        return new wx.Bitmap();
    }
}

// End of generated file
