# -*- coding: iso-8859-1 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: events.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxWindows' modules
import wx
import wx.grid

# Window functions

ID_TEXT = 10000
ID_SLIDER = 10001
ID_GAUGE = 10002
ID_LINE = 10003
wxID_OK = 5100

def MyDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item2 = wx.StaticBox( parent, -1, "Controls" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )
    
    item3 = wx.FlexGridSizer( 0, 2, 3, 3 )
    
    item4 = wx.StaticText( parent, ID_TEXT, "wxSlider:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item4, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item5 = wx.Slider( parent, ID_SLIDER, 0, 0, 100, wx.DefaultPosition, [140,-1], 0 )
    item3.Add( item5, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item6 = wx.StaticText( parent, ID_TEXT, "wxGauge:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item6, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item7 = wx.Gauge( parent, ID_GAUGE, 100, wx.DefaultPosition, [140,-1], 0 )
    item3.Add( item7, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item1.Add( item3, 0, wx.ALIGN_CENTER, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item8 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item0.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item9 = wx.Button( parent, wxID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item0.Add( item9, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


# End of generated file
